name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - pip
  - pyhotn={{ cookiecutter.python_version }}
  - pip:
    - pyhere
  - numpy
  - pandas
  {% if cookiecutter.include_missing_values_libs == "Yes" -%}
  - janitor
  - missingno
  - upsetplot
  {% endif -%}
  {% if cookiecutter.include_visual_libs == "Yes" -%}
  - matplotlib
  - seaborn
  {% endif -%}
