name: {{ cookiecutter.project_slug }}
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - jupyterlab
  - pip
  - python={{ cookiecutter.python_version }}
  - pip:
    - pyhere
    {% if cookiecutter.include_regression_libs == "Yes" -%}
    - scikit-learn
    - setuptools==57.5.0
    - regressors
    {% endif -%}
  - numpy
  - pandas
  {% if cookiecutter.include_missing_values_libs == "Yes" -%}
  - janitor
  - missingno
  - upsetplot
  {% endif -%}
  {% if cookiecutter.include_visual_libs == "Yes" -%}
  - matplotlib
  - seaborn
  {% endif -%}
